version: "2"

services:

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ~/docker/transmission/config:/config
      - ~/docker/transmission/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget
    volumes:
      - ~/docker/flexget/config:/config
      - ~/docker/transmission/torrents:/downloads
      - ~/docker/flexget/storage:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission
